name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Cleanup
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          go-mods: ./backend/go.mod

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./...
