name: CI & CD

on:
  push:
    branches: [ master ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./...

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "zeries-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "backend"
          healthcheck: "https://zeries-api.herokapp.com/api/ping"
          checkstring: "Pong!"
